### ISSUE TITLE
Failed to commit transaction  when drush-git already installed

### ISSUE THREAD

**Issue by socketwench** [jamesan/aur-pkgs#1]
If drush-git is already installed from AUR, the pacman -U step for the PKGBUILD fails:

```
error: failed to commit transaction (conflicting files)
drush-git: /usr/share/webapps/drush/composer.lock exists in filesystem
drush-git: /usr/share/webapps/drush/vendor/autoload.php exists in filesystem
drush-git: /usr/share/webapps/drush/vendor/bin/boris exists in filesystem
drush-git: /usr/share/webapps/drush/vendor/bin/phpunit exists in filesystem
drush-git: /usr/share/webapps/drush/vendor/composer/ClassLoader.php exists in filesystem
drush-git: /usr/share/webapps/drush/vendor/composer/autoload_classmap.php exists in filesystem
drush-git: /usr/share/webapps/drush/vendor/composer/autoload_namespaces.php exists in filesystem
drush-git: /usr/share/webapps/drush/vendor/composer/autoload_psr4.php exists in filesystem
```

...And everything else under /usr/share/webapps/drush/

**Comment by jamesan** [comment]
Sorry about that. This issue seems to be redundant now as I've modified the drush-git PKGBUILD to package drush as a PHAR. The listed files in this issue are now part of that PHAR [archive] and not standalone files to conflict with subsequent package upgrades.

If you can tell me which versions of the PKGBUILD you're upgrading between, I can re-run that specific upgrade path to isolate the bug. Most likely, the latest PKGBUILD is no longer affected by this issue. Please advise otherwise.
